### PR TITLE
docker fix

### PR DESCRIPTION
**Pull request by SetoKaiba**
https://github.com/MetaCubeX/subconverter/actions/runs/11365668185
@Larvan2 I found that the problem is caused by the lack of ARM/ARM64 environment.
So I remove the build of the ARM/ARM64 builidng.
It should fix the docker build now.

And here's the github action running without ARM/ARM64 in my repo.
And it successfully finished with merge job finished.
https://github.com/SetoKaiba/subconverter/actions/runs/11396629393
```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 860,
         "digest": "sha256:dead3d2d1bcdecb3bf44fa31c7b55185f7d39ee7e5e1e8586c23bfa835298f58",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 567,
         "digest": "sha256:eb68d1bd3f82e4103e89ccd4d18af5bd54908ed6cdfe33cd7b9635be7fac6037",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 860,
         "digest": "sha256:8281e310d0294c0508fe7e12e91130d835964e4002e17a113f9d0399ca4572ee",
         "platform": {
            "architecture": "386",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 567,
         "digest": "sha256:fa8440010183ea73f3fdfe357feec88aba47a841d560af785e6e2407dbcd1c99",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      }
   ]
}
```

### CODE REVIEW

**Comment by Larvan2** [comment]
https://github.com/MetaCubeX/subconverter/actions/runs/11451948896/workflow

Actually, the previous action for docker build works, and I've reset the commit to it currently.

**Comment by SetoKaiba** [comment]
@Larvan2 No. The build works but the manifest merge doesn't. It doesn't report an error for it. You can check the step here.
https://github.com/MetaCubeX/subconverter/actions/runs/11451948896/job/31862479373
Please check the Merge and push manifest on master branch.
```
Run python scripts/merge_manifest.py
ghcr.io/metacubex/subconverter@sha256:16a117c7f62ca0e8897c016d5e[4](https://github.com/MetaCubeX/subconverter/actions/runs/11451948896/job/31862479373#step:7:5)21a9a662c4f74af470f56ac2b6211577fd536 is a manifest list
No such manifest: ghcr.io/metacubex/subconverter:latest
```
The previous manifest merge is not working for multi-arch anymore.

You can check the commit in upstream probject here.
https://github.com/tindy2013/subconverter/commit/fb2aca323738f54e8c87d17b9bea411af0c1079b

You can use the command to inspect the docker build. Only ARM is available.
```
docker manifest inspect ghcr.io/metacubex/subconverter
```
You will see that only arm64 is available in the manifest. It means that the manifest merge failed.
Please have a check. Thank you.
```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 860,
         "digest": "sha256:055f9c5fe69afce221a263f48144bda5f79c16c223811e2cba73a17edbed00e7",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 566,
         "digest": "sha256:a0ab8fb83737ac43a15086afc790c39e88b3c0868c185680195273c073cc2289",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      }
   ]
}
```

**Comment by Larvan2** [comment]
That was my mistake. 

However, I believe the ARM build is worth keeping. Is it possible to retain the ARM build of Docker?

**Comment by SetoKaiba** [comment]
> That was my mistake.
> 
> However, I believe the ARM build is worth keeping. Is it possible to retain the ARM build of Docker?

@Larvan2 Can you please have a try on this? I have an update on it. It may help.

**Comment by SetoKaiba** [comment]
@Larvan2 It's finally fixed for docker. I check the manifest and the image. Both are correct. Thank you for the merging.

**Comment by Larvan2** [comment]
> @Larvan2 It's finally fixed for docker. I check the manifest and the image. Both are correct. Thank you for the merging.

Thanks for your great jobs 🎉.

**Pull request merged**
